root: ./

redirects:
  introduction/welcome-to-portkey: README.md
  introduction/getting-started: welcome/make-your-first-request.md.md
  introduction/features: README.md
  introduction/portkey-headers: api-reference/portkey-sdk-client.md
  portkey-features/ai-gateway: product/ai-gateway-streamline-llm-integrations.md
  portkey-features/ai-gateway/automatic-retries: product/ai-gateway-streamline-llm-integrations/automatic-retries.md
  portkey-features/ai-gateway/configs: product/ai-gateway-streamline-llm-integrations/configs.md
  portkey-features/ai-gateway/configs/how-to-use-configs: product/ai-gateway-streamline-llm-integrations/configs.md
  portkey-features/ai-gateway/simple-and-semantic-cache: product/ai-gateway-streamline-llm-integrations/cache-simple-and-semantic.md
  portkey-features/ai-gateway/fallbacks-on-llms: product/ai-gateway-streamline-llm-integrations/fallbacks.md
  portkey-features/ai-gateway/load-balancing: product/ai-gateway-streamline-llm-integrations/load-balancing.md
  portkey-features/observability: product/observability-modern-monitoring-for-llms.md
  portkey-features/observability/logs-and-analytics: product/observability-modern-monitoring-for-llms/logs.md
  portkey-features/observability/request-tracing: product/observability-modern-monitoring-for-llms/traces.md
  portkey-features/observability/custom-metadata: product/observability-modern-monitoring-for-llms/metadata.md
  portkey-features/model-management: product/prompt-library.md
  portkey-features/feedback: product/observability-modern-monitoring-for-llms/feedback.md
  portkey-features/security-and-compliance: product/ai-gateway-streamline-llm-integrations/virtual-keys.md
  portkey-features/security-and-compliance/virtual-keys: product/ai-gateway-streamline-llm-integrations/virtual-keys.md
  portkey-features/continuous-fine-tuning-beta: product/autonomous-fine-tuning.md
  sdk: api-reference/portkey-sdk-client.md
  sdk/python: api-reference/portkey-sdk-client.md
  sdk/node: api-reference/portkey-sdk-client.md
  integrations: welcome/integration-guides.md
  integrations/llm-providers: welcome/integration-guides.md
  integrations/llm-providers/open-ai-sdk: welcome/integration-guides/openai.md
  integrations/llm-providers/anthropic-sdk: welcome/integration-guides/anthropic.md
  integrations/llm-providers/whisper: api-reference/gateway-for-other-apis.md
  integrations/llm-providers/anyscale-llama-2-and-mistral-7b: welcome/integration-guides/anyscale-llama2-mistral-zephyr.md
  integrations/llm-providers/anyscale-llama-2-and-mistral-7b/fallback-to-llama2-70b-in-llamaindex: product/ai-gateway-streamline-llm-integrations/fallbacks.md
  integrations/llm-providers/cohere: welcome/integration-guides/cohere.md
  integrations/llamaindex: welcome/integration-guides/llama-index-python.md
  integrations/llamaindex/implementing-fallbacks-and-retries: welcome/integration-guides/llama-index-python.md
  integrations/llamaindex/implementing-load-balancing: welcome/integration-guides/llama-index-python.md
  integrations/llamaindex/implementing-semantic-caching: welcome/integration-guides/llama-index-python.md
  integrations/llamaindex/observability: welcome/integration-guides/llama-index-python.md
  integrations/langchain: welcome/integration-guides/langchain-python.md
  integrations/rest-api: api-reference/introduction.md
  integrations/rest-api/portkey-headers: api-reference/authentication.md
  cookbook: cookbooks/few-shot-prompting.md
  cookbook/few-shot-prompting: cookbooks/few-shot-prompting.md
  support-and-faq/why-portkey: README.md
  support-and-faq/why-portkey/observability: product/observability-modern-monitoring-for-llms.md
  support-and-faq/why-portkey/lower-cost-and-latency: welcome/make-your-first-request#is-my-data-secure.md
  support-and-faq/why-portkey/improve-llm-success-rate: welcome/make-your-first-request#is-my-data-secure.md
  support-and-faq/why-portkey/optimise-generation-quality: product/observability-modern-monitoring-for-llms.md
  support-and-faq/why-portkey/hide-pii-from-llms: welcome/make-your-first-request#is-my-data-secure.md
  support-and-faq/common-errors-and-resolutions: changelog/portkeys-december-migration.md
  overview/introduction: README.md
  overview/features-overview: README.md
  getting-started/setup-your-account: welcome/make-your-first-request.md
  getting-started/quick-integration: welcome/make-your-first-request.md
  how-portkey-works/portkey-modes: api-reference/introduction.md
  how-portkey-works/portkey-headers: api-reference/introduction.md
  how-portkey-works/supported-llms: welcome/integration-guides.md
  key-features/request-caching: product/ai-gateway-streamline-llm-integrations/cache-simple-and-semantic.md
  key-features/request-tracing: product/observability-modern-monitoring-for-llms/traces.md
  key-features/automatic-retries: product/ai-gateway-streamline-llm-integrations/automatic-retries.md
  key-features/custom-metadata: product/observability-modern-monitoring-for-llms/metadata.md
  key-features/fallbacks-on-llms: product/ai-gateway-streamline-llm-integrations/fallbacks.md
  key-features/load-balancing: product/ai-gateway-streamline-llm-integrations/load-balancing.md
  key-features/feedback-api: product/observability-modern-monitoring-for-llms/feedback.md
  key-features/logs-and-analytics: product/observability-modern-monitoring-for-llms/logs.md
  key-features/ai-provider-keys: product/ai-gateway-streamline-llm-integrations/virtual-keys.md
  key-features/prompt-management: product/prompt-library.md
  key-features/prompt-management/few-shot-prompting: cookbooks/few-shot-prompting.md
  integration-guides/open-ai-sdk: welcome/integration-guides/openai.md
  integration-guides/llamaindex: welcome/integration-guides/llama-index-python.md
  integration-guides/llamaindex/implementing-fallbacks-and-retries: welcome/integration-guides/llama-index-python.md
  integration-guides/llamaindex/implementing-load-balancing: welcome/integration-guides/llama-index-python.md
  integration-guides/llamaindex/implementing-semantic-caching: welcome/integration-guides/llama-index-python.md
  integration-guides/llamaindex/observability: welcome/integration-guides/llama-index-python.md
  integration-guides/langchain: welcome/integration-guides/langchain-python.md
  integration-guides/cohere: welcome/integration-guides/cohere.md
  integration-guides/anthropic-sdk: welcome/integration-guides/anthropic.md
  integration-guides/microsoft-guidance: welcome/integration-guides.md
  integration-guides/rest-api: api-reference/introduction.md
  why-portkey/observability: product/observability-modern-monitoring-for-llms.md
  why-portkey/lower-cost-and-latency: welcome/make-your-first-request#is-my-data-secure.md
  why-portkey/improve-llm-success-rate: welcome/make-your-first-request#is-my-data-secure.md
  why-portkey/optimise-generation-quality: product/observability-modern-monitoring-for-llms.md
  why-portkey/hide-pii-from-llms: welcome/make-your-first-request#is-my-data-secure.md
  troubleshooting-and-support/common-errors-and-resolutions: changelog/portkeys-december-migration.md
  open-source: open-source.md
  open-source/rubeus-by-portkey: open-source.md
  support-and-faq/join-portkey-on-discord: support/join-portkey-on-discord.md
  support-and-faq/contacting-support: support/contact-us.md
  support-and-faq/reporting-issues: support/common-errors-and-resolutions.md
  troubleshooting-and-support/reporting-issues: https://portkey.ai/docs/support/common-errors-and-resolutions.md
  troubleshooting-and-support/contacting-support: https://portkey.ai/docs/support/contact-us.md
  troubleshooting-and-support/join-portkey-on-discord: https://portkey.ai/docs/support/join-portkey-on-discord.md
